### ISSUE TITLE
add an option to change host

### ISSUE THREAD

**Issue by welandx** [skywind3000/vim-gpt-commit#1]
Many GPT applications can change the host:
https://github.com/skywind3000/vim-gpt-commit/blob/0c92af5ecd75d4a37fc52517221e26c33c872bea/bin/gptcommit.py#L22

**Comment by skywind3000** [comment]
fixed in :

https://github.com/skywind3000/vim-gpt-commit/commit/ca3887b70459a7254689458a6b5548720344b82c
